service: lampy-test

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  memorySize: 128
  timeout: 3

functions:
  handler:
    handler: index.handler
    events:
      - http:
          path: /
          method: get
          cors: true
